name: Generate LaTeX Bibliography

on:
  push:
    branches:
      - master  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up LaTeX
      uses: xu-cheng/latex-action@v2
      with:
        build_type: pdflatex

    - name: Compile LaTeX document
      run: |
        pdflatex -interaction=nonstopmode -halt-on-error lahti.tex
        bibtex lahti.aux
        pdflatex -interaction=nonstopmode -halt-on-error lahti.tex
        pdflatex -interaction=nonstopmode -halt-on-error lahti.tex

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v2
      with:
        name: pdf
        path: lahti.pdf
