name: Generate LaTeX PDF

on:
  push:
    branches:
      - master  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up LaTeX
      uses: xu-cheng/latex-action@v2
      with:
        build_type: latexmk
        root_file: lahti.tex  

    - name: Compile LaTeX document
      run: |
        latexmk -pdf -file-line-error -halt-on-error -interaction=nonstopmode your_document.tex

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v2
      with:
        name: pdf
        path: lahti.pdf
