name: Generate LaTeX PDF

on:
  push:
    branches:
      - master  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-full  # Install a full TeX Live distribution
        sudo apt-get install -y latexmk      # Install latexmk
        sudo apt-get install -y biber        # Install biber for bibliography (if needed)

    - name: Compile LaTeX document
      run: |
        latexmk -pdf -file-line-error -halt-on-error -interaction=nonstopmode lahti.tex

      - name: Configure Git
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your-email@example.com'
          
      - name: Commit PDF
        run: |
          git add Leo_Lahti.pdf
          git commit -m "Add generated PDF"
          git push origin master
